import os

from checks.base import Checker
from problem import Problem, Severity

class CommentsChecker(Checker):
    SUSPICIOUS = [
        "do not modify this file",
        "do not edit this file",
        "do not edit by hand",
        "do not modify by hand",
        "file was generated by",
        "this was generated by",
        "it was generated by"
    ]

    # Checks for common strings that indicate generated files
    def execute(self, file: str) -> Problem | None:
        with open(file, "rb") as f:
            text = f.read()
            for string in self.SUSPICIOUS:
                for variant in [string, string.capitalize(), string.upper()]:
                    if variant.encode("utf-8") in text:
                        return Problem(Severity.WARN, f"{variant} may indicate this file is generated")
        return None
