import os
import magic
import re

from checks.base import Checker
from problem import Problem, Severity

class DocbookChecker(Checker):
    def execute(self, file: str) -> Problem | None:
        mime = magic.from_file(file, mime=True)
        if re.match(r".*\.(?:[1-9]|man)$", file) or mime == "text/troff" or self._text_deep(file):
            with open(file, "rb") as f:
                if b"Generator: DocBook XSL Stylesheets" in f.read():
                    return Problem(Severity.ERROR, "generated by DocBook XSL Stylesheets")
