import magic
import os

from checks.base import Checker
from problem import Problem, Severity

class FlexChecker(Checker):
    MAGIC = 0xF1E8

    def execute(self, file: str) -> Problem | None:
        mime = magic.from_file(file, mime=True)
        if file.endswith(".c") or mime == "text/x-c" or self._text_deep(file):
            with open(file, "rb") as f:
                if b"lexical scanner generated by flex" in f.read():
                    return Problem(Severity.ERROR, "generated by flex", file, self.MAGIC)
            lex_file = file.removesuffix(".c") + ".l"
            if os.path.isfile(lex_file):
                return Problem(Severity.WARN, f"may be generated from {lex_file} by flex", file, self.MAGIC)

        if os.path.basename(file) == "lex.yy.c":
            return Problem(Severity.WARN, "common name for generated lex file", file, self.MAGIC)
        
        return None
